name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: jtstothard/bastardkb-qmk
      qmk_ref: maxtouch-dpi-fix

  publish:
    name: 'QMK Userspace Publish'
    uses: bastardkb/qmk_userspace/.github/workflows/qmk_userspace_publish_develop.yml@develop
    if: always() && !cancelled()
    needs: build
